name: Autotests

on: [push]

jobs:
  build:
    name: Application Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore ./healthino.csproj
      - name: Build
        run: dotnet build healthino.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test healthino.csproj --no-restore --verbosity normal
  
  publish:
    name: Deploy to Server
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore ./healthino.csproj
      - name: Publish
        run: dotnet publish ./healthino.csproj --output bin/publish --framework net6.0 --no-self-contained

      - name: Prepare and copy to staging, deploy to production
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'bin/publish/*'
          remote: ${{ format('{0}/staging/', secrets.SERVER_TARGET_DIRECTORY) }}
          host: ${{secrets.SERVER_HOST}}
          user: ${{secrets.SERVER_USER}}
          password: ${{secrets.SERVER_PASSWORD}}
          pre_upload: echo "sh ./prepare.sh"
          post_upload: echo "sh ./deploy.sh"
